### ISSUE TITLE
Automatically backup notes

### ISSUE THREAD

**Issue by HarriBuh** [maelchiotti/LocalMaterialNotes#105]
I like your app so far, especially the export as JSON- and the list-feature.

What I really miss though, are JSON backups being automatically encrypted and automatic backups at least once a day.

**Comment by maelchiotti** [comment]
Hi, thank you for using the app and letting me know you like it!

Automatic backups would make sense and should not be to hard to implement, I will look into it for the next release.

As for encryption, I created another issue, please see #106.

**Comment by maelchiotti** [comment]
Hi @HarriBuh, I've added auto backups in #114. You can set the frequency from each day to each 30 days. It will be available in the next release.

I'm looking into encrypting them, as it's not too difficult.
