### ISSUE TITLE
App running at 60Hz

### ISSUE THREAD

**Issue by adarsh1001** [maelchiotti/LocalMaterialNotes#111]
Hey, thanks for the clean and beautiful notes app!

So for Flutter apps, this is a common issue with variable refresh rate devices. All other apps run at 120Hz on my device but some flutter apps like this one are capped to 60Hz. There's a simple fix for this done here:

https://github.com/emavgl/oinkoin/issues/16#issuecomment-1823492267

Device: Nothing Phone (2)
OS: Android 14

**Comment by maelchiotti** [comment]
Oh, thank you for letting me know, I had no idea! This is fixed in #112 and will be available in the next release. Glad you enjoy the app!
