### ISSUE TITLE
Add Russian language

### ISSUE THREAD

**Issue by shishkevichd** [maelchiotti/LocalMaterialNotes#113]

**Comment by maelchiotti** [comment]
Hi @shishkevichd, thank you for offering to add Russian language support! I just added it to the Crowdin project, you should be able to see the "Join" button.

**Comment by maelchiotti** [comment]
Just accepted!

**Comment by shishkevichd** [comment]
> Just accepted!

Thanks!

**Comment by maelchiotti** [comment]
Thank you for translating the app in russian @shishkevichd! It will be available in the next release. Feel free to come back to the Crowdin projet when you wish to, if you want to keep the translation up to date ☺️
