### ISSUE TITLE
Encryption and Password Protect

### ISSUE THREAD

**Issue by super-lurker** [maelchiotti/LocalMaterialNotes#116]
encrypt and password protect the app, I am surprise that this is not a standard feature on most note apps, considering the amount of personal data you write on them.

**Comment by maelchiotti** [comment]
Hi, indeed, that would be great. Someone else already requested that, see #105 and #106.

So I'll close this as duplicate, but feel free to continue the discussion in #106!

**Comment by super-lurker** [comment]
my bad, the one time i dont use search, i hate duplicates, and i hate making them even more

**Comment by maelchiotti** [comment]
That's okay don't worry, happens to everyone 😊
