### ISSUE TITLE
[BUG] App will always open the same note again after automatic sorting

### ISSUE THREAD

**Issue by HarriBuh** [maelchiotti/LocalMaterialNotes#142]
I'm not entirely sure about the "how", but the app now keeps opening the same note, no matter what note I choose.

The title changes accordingly, but not the content.

Since there is no crash or error, there are no logs I could provide.

I am 90% sure it started to occur after I chose the automatic sorting option for the first time.
- Manual quitting didn't help
- Cleaning the cache didn't help
- Completely resetting the app (and re-importing a backup) didn't help

**Comment by maelchiotti** [comment]
And this month I'll (finally) heavily work on automated tests, to avoid annoying regressions like this 😅

**Comment by maelchiotti** [comment]
Also, can you detail what you meant about the wrong mutated vowel? Preferably in a different issue if it is one.

**Comment by maelchiotti** [comment]
I did it in #143. I'm pretty sure I just need to add encoding, I remember doing it for the content but not the title.

**Comment by maelchiotti** [comment]
@HarriBuh fixed in the new [v1.5.1](https://github.com/maelchiotti/LocalMaterialNotes/releases/tag/v1.5.1), as well as the import encoding issue ☺️

**Comment by maelchiotti** [comment]
Luckily I was free tonight. Hope it is truly fixed!
