### ISSUE TITLE
Slim notes list with only the titles

### ISSUE THREAD

**Issue by smaragdus** [maelchiotti/LocalMaterialNotes#150]
Please consider adding an option for slim notes list where only the titles of the notes are shown, without preview, just like in [Simplenote](https://github.com/Automattic/simplenote-android), screen:

![Screenshot_2024-08-11-01-18-32-423_com automattic simplenote](https://github.com/user-attachments/assets/cf286793-438b-46a9-a748-11c283e4b15e)

The new option may be added under **Appearance** in **Settings**:

- **Notes List - No preview**

or

- **Notes List - Titles only**

Besides looking better (at least for me) another advantage would be less scrolling- this option would be especially useful when the users have a huge number of notes.

I suppose this option would not be hard to be implemented.

Regards

**Comment by maelchiotti** [comment]
This is a very good idea and would be easy to implement indeed, I will add it to the next release.

**Comment by maelchiotti** [comment]
@smaragdus Hi, I couldn't include this in today's release but it will be available in the next one!

**Comment by smaragdus** [comment]
@maelchiotti 

Don't worry, I am not in a hurry at all. It is just that I follow new apps via F-droid, test some of them and sometimes I request new features. If you don't mind I might add new feature requests in the future. I wish that free and open source apps get better and better.

**Comment by maelchiotti** [comment]
Of course, open as many feature requests as you want!

**Comment by NripPrajapat** [comment]
Provide an option to choose, how many lines should be visible on main screen with a adjustable seek bar, like 1-10 lines maybe. It is fixed at 3 lines right now.

**Comment by maelchiotti** [comment]
Great idea, new issue for that: #354
