### ISSUE TITLE
Fix the back action

### ISSUE THREAD

**Issue by maelchiotti** [maelchiotti/LocalMaterialNotes#166]
There is still an issue when going back (with the system navigation) after closing a dialog or sheet: it closes the app instead of going back, even though the app back button works fine.

**Comment by uli-on** [comment]
The same happens, BTW, when pressing the Back button after opening one of the search results.

**Comment by maelchiotti** [comment]
Oh you're right. I'm opening an issue on the routing library next weekend because I can't figure out what I'm doing wrong.

**Comment by uli-on** [comment]
[[Is the search term persistent? (Can't try out ;) I. e. press back in an opened note, and the filtered list is still there?]]

**Comment by maelchiotti** [comment]
No, the search view is closed when you tap on a search result. That's how it's designed by default by the framework.

You can see that using the back button inside the app goes back to the notes list as it should. Looks like closing something (the search view, a drawer, a menu) confuses the system back button/gesture somehow.

**Comment by maelchiotti** [comment]
@uli-on @itsmartashub I've FINALLY managed to fix this, took 2 hours of trying things out to determine where the issue was coming from. Now the back actions works correctly everywhere: bottom sheets, popup menus, dialogs, search view... The fix will be included in the next release!

**Comment by uli-on** [comment]
Ooooh 😵‍💫, sorry! And thanks so much!

**Comment by itsmartashub** [comment]
Oh my, two hours deep in debugging hell 😮‍💨 Thank you so much for your patience and willingness to resolve the routing issue!
