### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by UserAccount123** [maelchiotti/LocalMaterialNotes#172]
SUGGESTIONS:
- [ ] 1-1. Checkboxes: add option to move checked items to the bottom + Ability to convert checkbox line to a normal text line + Add (X) beside ckeckbox line + Enable swipe right/left to add color to the line + Add more space between lines with checkboxes.
- [ ] 1-2. Make (=) reorder mark always visible (and when moving an item among items .. Add a temporary grey color to it + If someone want to move many items together .. Add an ability to temporarily group list items so as to move them together.
- [ ] 1-3. FEATURE: Swipe left a list item to change it to a normal line (without checkbox) + Swipe right to add color to it; this idea comes from the idea of: similar items must get the same color.
- [ ] 2. (+) Button: enable swiping up to add list note + long press to show hidden/locked notes.
- [ ] 3. Add (Lock with PIN) feature.
- [ ] 4. Settings > Behavior > Swipe: add (Lock, hide, favorite).
- [ ] 5. Main screen (Notes):
- Enable adding color to notes.
- Add ability to group notes by: Color (deny/forbid moving a note away from notes with same color), Modification date, Creation date and Alphabetically (ascending/descending) + Allow manual sorting.
- Ability to change font size of notes viewed in main screen + Ability to specify numbers of lines to show.
- [ ] 6. Allow adding color to text + Adding highlight color around text.
- [ ] 7. Ability to only show title of the note (hiding its content) + if searching a word, temporarily disable (Show only title) option if it's enabled.
- [ ] 8. Ability to hide/show (creation/modification) date in note.
- [ ] 9. Search:
- Automatically highlight all the texts with color, and add ability to go to them by arrow buttons.
- Add ability to search inside the note + Keep highlighting active until you cancel it (because it better to keep it active; so as to edit in all the highlighted words).
- [ ] 10. Option to highlight: (Link, Email, Phone number), and when touching it, make many options appear: Open (opens Link & Email, but for phone number > put it in phone dialer), Copy, or Edit.
- [ ] 11. Ability to insert clipboard text by floating shape or by showing the clipboard text as a floating object.
- [ ] 12. Add (Info) feature which includes: [Character count (including whitespaces) + Words count + Number of lines + Creation/Modification date and time].
- [ ] 13. Add (Copy note content to clipboard) feature for note & checklist.
- [ ] 14. Ability to attach: Images (images, created drawing, camera), Video, Audio, Record or any type of files + Ability to export these attachments with the note.
- [ ] 15. NEW = add (Replace text) feature for note/checklist, AND an ability to replace multiple texts (separated by comma (,)) in multiple notes/checklists + Ability to replace text while editing a note/checklist.
- [ ] 16. Ability to import TXT file/files.
- [ ] 17. Ability to select the focused field when creating a new note: to be the title or the description.
- [ ] 18. When opening a note with text .. Add an option automatically scroll to: the beginning of text, the end or the last cursor's position.
- [ ] 19. Ability to export multiple selected notes (TXT, PNG/JPG, PDF).
- [ ] 20. Ability export/import to/from Google Drive.

**Comment by maelchiotti** [comment]
Thank you for the many suggestions. I am closing the issue since it does not need to stay opened, but I will go through the list to see what I'm interested in adding to the app!

**Comment by uli-on** [comment]
@UserAccount123 I've tried out 80+ apps for taking notes and none(!) of them can cover only 10 % of your list. The one closest to your imagination seems to be Quillpad.

**Comment by maelchiotti** [comment]
Yeah I took those just as suggestions to pick from (and I did pick implement 1 or 2).
