### ISSUE TITLE
Add copy to clipboard action + swipe action + share swipe action

### ISSUE THREAD

**Issue by franco27** [maelchiotti/LocalMaterialNotes#190]
Hello.  
I just discovered your application.  

And it's a shame that for a note, there isn't a menu to send the text to the clipboard in plain text.  

I saw there was a Share button or menu, but it's not the same.

**Comment by maelchiotti** [comment]
Great idea, I will add it for the next release.

I will also add it to the possible swipe actions, along with "share".

Do you think only the content should be copied to the clipboard? Or also the title, like with the share action? Maybe I could make this configurable in the settings?

**Comment by franco27** [comment]
You should only send the content to the clipboard and not the title.
