### ISSUE TITLE
Remove EXTERNAL_STORAGE permissions

### ISSUE THREAD

**Issue by IzzySoft** [maelchiotti/LocalMaterialNotes#201]
The scanner at IzzyOnDroid reported:

```
! repo/com.maelchiotti.localmaterialnotes_142.apk declares sensitive permission(s):
  android.permission.READ_EXTERNAL_STORAGE
```

Could you please clarify why this permission is needed? I see in #141 that you're using SAF, so I wonder what for the "old" storage permissions (both, READ + WRITE) are needed here.

**Comment by maelchiotti** [comment]
I did not add this permission myself, it appears to be the library I used in #141: [here](https://github.com/maelchiotti/shared_storage/blob/v0.8.1_fixed/android%2Fsrc%2Fmain%2FAndroidManifest.xml).

I don't really know why the author added it or if it is required, since I forked the package because it's no longer maintained I'll try to remove it to see if it works without it.

**Comment by IzzySoft** [comment]
> SAF really is a pain to work with in Flutter...

Overly specific dementi. Let's make that "SAF really is a pain to work with" – at least from Android 9 to 11, where each release deals with it differently, needs different combinations of permissions etc. And yeah, not the first time I read there seems to be no maintained Flutter package for SAF, which came to me as a real surprise – as since Lollipop that should be the way to go… There are several packages, yes – but an up-to-date and maintained one? I don't know. Let me check my library definitions with `grep -i storage libinfo.jsonl | grep -i flutter`:

```json
{"id": "/boaventura/com/devel/br/flutteraudioquery", "emphasize": 0, "details": "Flutter plugin that allows you query for audio metadata info about artists, albums, songs audio files and genres available on device storage.", "mwid": "", "anti": [], "license": "MIT"}
{"id": "/com/amudanan/path_provider_ex", "emphasize": 0, "details": "an Android path provider for Flutter that provides root and app files directory for both „external storage“ (internal flash) and SD card (if present), as well as available space for each storage.", "mwid": "", "anti": [], "license": "MIT"}
{"id": "/com/github/yasukotelin/ext_storage", "emphasize": 0, "details": "a minimal flutter plugin that provides external storage path and external public storage path.", "mwid": "", "anti": [], "license": "MIT"}
{"id": "/com/it_nomads/fluttersecurestorage", "emphasize": 0, "details": "a Flutter plugin to store data in secure storage (Keychain, AES-encryption).", "mwid": "", "anti": [], "license": "BSD-3-Clause"}
{"id": "/com/lucasjosino/on_audio_query", "emphasize": 0, "details": "Flutter Plugin used to query audios/songs infos [title, artist, album, etc..] from device storage. ", "mwid": "", "anti": [], "license": "BSD-3-Clause"}
{"id": "/design/codeux/biometric_storage", "emphasize": 0, "details": "Flutter plugin to store data behind biometric authentication (ie. fingerprint).", "mwid": "", "anti": [], "license": "MIT"}
{"id": "/io/flutter/plugins/sharedpreferences", "emphasize": 0, "details": "wraps platform-specific persistent storage for simple data.", "mwid": "", "anti": [], "license": "BSD-3-Clause"}
```

If any of that sounds helpful to you, the source repos are in [`libsmali.jsonl`](https://gitlab.com/IzzyOnDroid/repo/-/blob/master/lib/libsmali.jsonl).

Thanks for your efforts! Looking forward to the progress then.

**Comment by maelchiotti** [comment]
Yeah, in my opinion it should be Google's job to support such an important feature of Android in Flutter just like in native development, but they just don't...

The packages you listed are related to storage indeed, but sadly none are related to SAF nor can be used as an alternative.

The only two packages implementing SAF that I found are the one I mentioned, which is explicitly marked as discontinued, and one simply called "saf" that received no updates for like 2 years and is hardly usable.

**Comment by maelchiotti** [comment]
By digging through pub.dev and GitHub, I ended up finding safe_util and saf_stream that are very actively developed and seem really great, so I have good hopes that they will fix everything! Crazy how pub.dev burries them far aways in the search results even when I search for "saf"...

**Comment by IzzySoft** [comment]
The [Github repo of saf_util](https://github.com/flutter-cavalry/saf_util) gives me a 404 (I wonder were it moved to, with the last release not even 2 days ago – it says BSD-3-Clause, so the code must be somewhere) – but saf_stream seems to be still there, alive and kicking. Glad you found something! I've just added the latter to my library definitions.

**Comment by maelchiotti** [comment]
Since saf_utils seems very recent, I guess they had some reason to make it private temporarily or something. But yes, those packages look promising!

**Comment by IzzySoft** [comment]
Exactly my thoughts, yeah :smiley: Thanks for digging that up!

**Comment by maelchiotti** [comment]
Happy to report that the packages work very well! So the fix is on its way.

**Comment by maelchiotti** [comment]
And the saf_utils package is back online @IzzySoft!

**Comment by IzzySoft** [comment]
Thanks for the note! Added to the library definitions here (so becoming publicly available with the next `git push` there).

**Comment by IzzySoft** [comment]
They are primarily used by my library scanner (see e.g. [Identify modules in apps](https://android.izzysoft.de/articles/named/app-modules-2)), but also by other projects. And as shown, as a side-effect I can skim them when looking for specific libraries – in the case here, "a Flutter package for storage handling". Scanner & libs are FOSS, the linked article also includes where to find them (and how to use the scanner for yourself) should you be interested.
