### ISSUE TITLE
Delete blank notes

### ISSUE THREAD

**Issue by itsmartashub** [maelchiotti/LocalMaterialNotes#234]
When creating a new note and entering only spaces (e.g., single or multiple space characters), the note gets saved as a "blank" entry. I'm not sure if this is the expected behavior, or if the note should be trimmed of leading/trailing spaces to avoid saving blank or unnecessary entries.

![Screenshot_2024-10-19-20-46-54-892_com.maelchiotti.localmaterialnotes.jpg](https://github.com/user-attachments/assets/37393d48-b835-4d96-bd6e-dddcc2ac9d6a)

**Comment by maelchiotti** [comment]
Yeah, I don't know how those should be handled. Only blank spaces could be considered an empty note. I'll look at how other apps handle this.

**Comment by maelchiotti** [comment]
Simplenote doesn't care about empty notes, but Another Notes deletes them even with spaces. I will do the same as it makes sense in my opinion.

**Comment by maelchiotti** [comment]
Well, I won't 🥲.

I just realized that since the data format of the content is way more complicated than just text, I can't easily check what's inside or not - I can just check whether it's empty.
