### ISSUE TITLE
Auto-create note from shared text

### ISSUE THREAD

**Issue by itsmartashub** [maelchiotti/LocalMaterialNotes#235]
When sharing selected text from a website to Material Notes, the note should be created automatically include:

- The selected text as content
- The source URL in the note
- The website title as the note title

For apps where no URL/title, it can just save the selected text (similar to other note apps)

### Steps:

- Select text from a website or app (e.g., Twitter etc)
- Share it to the note app

### Expected:

- The note is created automatically with appropriate content, URL, and title (if applicable)

### Example ([Another Notes](https://github.com/maltaisn/another-notes-app)):
![Screenshot_2024-10-19-21-08-34-748_com.maltaisn.notes.sync.jpg](https://github.com/user-attachments/assets/d35e672d-8af1-43d7-8272-232d165ad163)

Select the content of example.com website and shared to the Another Notes app (it's the same with [Quillpad](https://github.com/quillpad/quillpad) note app, but unfortunately idk any Flutter note app which source code could be useful for this feature :()

**Comment by maelchiotti** [comment]
I use a library to handle that, I'll look at what data it provides and if I discarded some.

**Comment by maelchiotti** [comment]
Weirdly, after testing with Another Notes on two different devices (Android 12 with MIUI and Android 14 Pixel) I get different results. Mine don't include the link, and as a title I get "Including link:" or "Sharing with". Pixel also adds `"` around the text.

I would not be surprised if the sharing functionality in Android was a bit of a mess, with changes across versions and manufacturers. 

So I don't think I'll dig too much into this 😅
