### ISSUE TITLE
Add drag and drop for checkbox items

### ISSUE THREAD

**Issue by TheFuzzStone** [maelchiotti/LocalMaterialNotes#249]
![Screenshot_20241109-174904](https://github.com/user-attachments/assets/d3a7a6f6-1041-4bdb-81cf-f3c26cbad609)

**Comment by maelchiotti** [comment]
Hi, that would be nice indeed. However, I use an external library for the editor, and I highly doubt they will ever add such a functionality, as they are a small 2-persons team. For this reason, I'll close this as not planned.

**Comment by TheFuzzStone** [comment]
:(

**Comment by maelchiotti** [comment]
Sorry, rich text editors are very complicated to develop, so it's pretty rare to find such a functionality included a library, and I clearly don't have the capability to do it myself :(

**Comment by TheFuzzStone** [comment]
@maelchiotti, I understand, thanks for answering.

I just like minimalism in FOSS and I don't like to have several applications for one function. There is for example this one: https://github.com/OmGodse/Notally, it's good, but I like the approach and logic in your app, that I don't need a separate function to create just a note and a separate function to create just a list with checkboxes...

But, being able to rearrange checkboxes is a very handy feature.

**Comment by maelchiotti** [comment]
Yes, I completely agree! I hate to have my text separated from my checklists.

But I'm pretty sure they do it exactly for the reason I mentioned: it's way easier to add functionalities such as drag and drop when the checklist are just tiles you can re-arrange, and not lines in a text.
