### ISSUE TITLE
Instant crash on app startup (1.8.0)

### ISSUE THREAD

**Issue by HarriBuh** [maelchiotti/LocalMaterialNotes#259]
Google Pixel 7
Android 15
(Downgrading back to 1.7.2 "fixes" the issue)

┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ Invalid argument (name): No enum value with that name: "date"
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   EnumByName.byName (dart:core/enum.dart:168)
│ #1   new SortMethod.fromPreference (package:localmaterialnotes/common/preferences/enums/sort_method.dart:26)
│ #2   NotesAppBar.build (package:localmaterialnotes/common/navigation/app_bars/notes_app_bar.dart:123)
│ #3   _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:476)
│ #4   StatefulElement.build (package:flutter/src/widgets/framework.dart:5729)
│ #5   ConsumerStatefulElement.build (package:flutter_riverpod/src/consumer.dart:539)
│ #6   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5617)
│ #7   StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
│ #8   Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
│ #9   ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
│ #10   StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
│ #11   ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
│ #12   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #13   Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
│ #14   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
│ #15   StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
│ #16   Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
│ #17   ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
│ #18   StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
│ #19   ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
│ #20   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #21   Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
│ #22   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
│ #23   StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
│ #24   Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
│ #25   ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
│ #26   StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
│ #27   ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
│ #28   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #29   Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
│ #30   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
│ #31   Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
│ #32   ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
│ #33   ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
│ #34   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #35   Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
│ #36   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
│ #37   Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
│ #38   ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
│ #39   ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
│ #40   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #41   Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
│ #42   SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
│ #43   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #44   Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
│ #45   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
│ #46   Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
│ #47   ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
│ #48   ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
│ #49   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #50   Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
│ #51   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
│ #52   Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
│ #53   ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
│ #54   ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
│ #55   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #56   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7035)
│ #57   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7047)
│ #58   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #59   Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
│ #60   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
│ #61   Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
│ #62   ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
│ #63   ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
│ #64   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #65   Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
│ #66   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
│ #67   StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
│ #68   Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
│ #69   ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
│ #70   StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
│ #71   ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
│ #72   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #73   Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
│ #74   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
│ #75   StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
│ #76   Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
│ #77   ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
│ #78   StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
│ #79   ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
│ #80   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #81   Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
│ #82   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
│ #83   Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
│ #84   ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
│ #85   ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
│ #86   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #87   Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
│ #88   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
│ #89   StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
│ #90   Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
│ #91   ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
│ #92   StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
│ #93   ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
│ #94   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #95   Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
│ #96   SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
│ #97   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #98   Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
│ #99   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ 2024-11-23 19:07:59.506
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ Invalid argument (name): No enum value with that name: "date"
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ Invalid argument (name): No enum value with that name: "date"
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   EnumByName.byName (dart:core/enum.dart:168)
│ #1   new SortMethod.fromPreference (package:localmaterialnotes/common/preferences/enums/sort_method.dart:26)
│ #2   Note.compareTo (package:localmaterialnotes/models/note/note.dart:232)
│ #3   Comparable.compare (dart:core/comparable.dart:88)
│ #4   ListBase._compareAny (dart:collection/list.dart:325)
│ #5   Sort._insertionSort (dart:_internal/sort.dart:69)
│ #6   Sort._doSort (dart:_internal/sort.dart:58)
│ #7   Sort.sort (dart:_internal/sort.dart:33)
│ #8   ListBase.sort (dart:collection/list.dart:321)
│ #9   IterableComparableExtension.sorted (package:collection/src/iterable_extensions.dart:938)
│ #10   Notes.get (package:localmaterialnotes/providers/notes/notes/notes_provider.dart:32)
│ #11   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ 2024-11-23 19:07:59.519
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ Invalid argument (name): No enum value with that name: "date"
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ Invalid argument (name): No enum value with that name: "date"
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   EnumByName.byName (dart:core/enum.dart:168)
│ #1   new SortMethod.fromPreference (package:localmaterialnotes/common/preferences/enums/sort_method.dart:26)
│ #2   NotesAppBar.build (package:localmaterialnotes/common/navigation/app_bars/notes_app_bar.dart:123)
│ #3   _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:476)
│ #4   StatefulElement.build (package:flutter/src/widgets/framework.dart:5729)
│ #5   ConsumerStatefulElement.build (package:flutter_riverpod/src/consumer.dart:539)
│ #6   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5617)
│ #7   StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
│ #8   Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
│ #9   ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
│ #10   StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
│ #11   ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
│ #12   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #13   Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
│ #14   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
│ #15   StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
│ #16   Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
│ #17   ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
│ #18   StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
│ #19   ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
│ #20   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #21   Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
│ #22   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
│ #23   StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
│ #24   Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
│ #25   ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
│ #26   StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
│ #27   ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
│ #28   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #29   Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
│ #30   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
│ #31   Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
│ #32   ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
│ #33   ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
│ #34   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #35   Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
│ #36   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
│ #37   Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
│ #38   ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
│ #39   ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
│ #40   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #41   Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
│ #42   SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
│ #43   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #44   Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
│ #45   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
│ #46   Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
│ #47   ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
│ #48   ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
│ #49   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #50   Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
│ #51   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
│ #52   Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
│ #53   ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
│ #54   ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
│ #55   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #56   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7035)
│ #57   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7047)
│ #58   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #59   Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
│ #60   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
│ #61   Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
│ #62   ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
│ #63   ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
│ #64   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #65   Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
│ #66   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
│ #67   StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
│ #68   Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
│ #69   ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
│ #70   StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
│ #71   ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
│ #72   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #73   Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
│ #74   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
│ #75   StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
│ #76   Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
│ #77   ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
│ #78   StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
│ #79   ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
│ #80   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #81   Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
│ #82   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
│ #83   Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
│ #84   ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
│ #85   ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
│ #86   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #87   Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
│ #88   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
│ #89   StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
│ #90   Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
│ #91   ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
│ #92   StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
│ #93   ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
│ #94   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #95   Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
│ #96   SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
│ #97   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
│ #98   Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
│ #99   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ 2024-11-23 19:08:19.359
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ Invalid argument (name): No enum value with that name: "date"
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ Invalid argument (name): No enum value with that name: "date"
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   EnumByName.byName (dart:core/enum.dart:168)
│ #1   new SortMethod.fromPreference (package:localmaterialnotes/common/preferences/enums/sort_method.dart:26)
│ #2   Note.compareTo (package:localmaterialnotes/models/note/note.dart:232)
│ #3   Comparable.compare (dart:core/comparable.dart:88)
│ #4   ListBase._compareAny (dart:collection/list.dart:325)
│ #5   Sort._insertionSort (dart:_internal/sort.dart:69)
│ #6   Sort._doSort (dart:_internal/sort.dart:58)
│ #7   Sort.sort (dart:_internal/sort.dart:33)
│ #8   ListBase.sort (dart:collection/list.dart:321)
│ #9   IterableComparableExtension.sorted (package:collection/src/iterable_extensions.dart:938)
│ #10   Notes.get (package:localmaterialnotes/providers/notes/notes/notes_provider.dart:32)
│ #11   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ 2024-11-23 19:08:19.372
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ Invalid argument (name): No enum value with that name: "date"
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by maelchiotti** [comment]
Thank you for the report and the logs, I'm fixing this right now and publishing a new version.

**Comment by maelchiotti** [comment]
@HarriBuh this should be fixed with https://github.com/maelchiotti/LocalMaterialNotes/releases/tag/v1.8.1
