### ISSUE TITLE
Something broke

### ISSUE THREAD

**Issue by MillionsToOne** [maelchiotti/LocalMaterialNotes#263]
In version 1.8.1, it seems something broke.

https://github.com/user-attachments/assets/d4e0e5e6-2634-4d46-b1ff-1783b4a86d43

**Comment by maelchiotti** [comment]
That is weird. Can you copy the logs from the settings, about section and paste them here?

**Comment by maelchiotti** [comment]
Never mind, managed to reproduce it. Working on that third release today...

**Comment by maelchiotti** [comment]
Fix is being released, hope you can finally enjoy the new labels 🙏
