### ISSUE TITLE
Coloured card

### ISSUE THREAD

**Issue by NripPrajapat** [maelchiotti/LocalMaterialNotes#267]
Add an option to make notes card colourful in main view at least.

**Comment by NripPrajapat** [comment]
Or simply take the assigned colour and apply it to labeled whole card.

**Comment by maelchiotti** [comment]
This was requested in #70. I won't implement it because notes can already be categorized with labels now, so I feel it would be redundant to also be able to choose a color for each note, and I would take away from the simplicity of the app.

**Comment by NripPrajapat** [comment]
Okay, it's up to you, anyway. But it surely would've looked better and attractive.

**Comment by maelchiotti** [comment]
I know I personally like that all the app as the same color overall, so I wouldn't like each note to be a different color. But I understand you might feel differently! Hope you can still enjoy the app without that feature.

**Comment by NripPrajapat** [comment]
You have seen the DNotes and Keep, they all do this and they look great, give it time.
Maybe one day, you'll like it, I'll wait till that day. Cheers.
Don't be upset with me for this constant nagging.

**Comment by maelchiotti** [comment]
Not upset at all, glad you enjoy the app enough to want it to be improved with features you like 😊

You'll be the first to know if I change my mind!
