### ISSUE TITLE
Import from DNotes

### ISSUE THREAD

**Issue by NripPrajapat** [maelchiotti/LocalMaterialNotes#268]
Any way I could import text file?

Actually I am currently using DNotes, I want to import all my 3000+ notes to this app, is there any workaround?

**Comment by maelchiotti** [comment]
The best way to do that would be to convert that text file to a JSON file with the format used by Material Notes.

Can you code in pyhton? Another user made [a script](https://github.com/maelchiotti/LocalMaterialNotes/blob/main/docs/external_imports/samsung_notes.py) to convert Samsung Notes exports, you could use it as a base. If you don't, I will try to find the time to write the script for you.

**Comment by NripPrajapat** [comment]
I am sorry, but I don't know coding, I would really appreciate if you do that.
Or guide me how to do that, whichever suits you better.
Regards.

**Comment by maelchiotti** [comment]
I'll take a look when I find the time.

Is it this app you are using?
https://play.google.com/store/apps/details?id=com.dvdb.bergnotes

**Comment by NripPrajapat** [comment]
Yes, that is the app.

**Comment by maelchiotti** [comment]
At first glance, I see it allows to create multiple types of notes. Text notes shouldn't be an issue, but I'm note sure about the other types. I'll let you know when I work on it.

**Comment by NripPrajapat** [comment]
Great, will be eagerly waiting.

**Comment by maelchiotti** [comment]
@NripPrajapat I'm writing the script, it's working with my little test I created. But I'd like to try on a bigger dataset. Are you comfortable sharing your export with me (via [email](mailto:contact@maelchiotti.dev)), or do they contain too much personal information?

**Comment by NripPrajapat** [comment]
[d_notes_202411302056.zip](https://github.com/user-attachments/files/17965908/d_notes_202411302056.zip)

Here it is.

**Comment by maelchiotti** [comment]
@NripPrajapat Ok the script works well.

I see you have notes with categories, would you also like categories to be converted to labels?

**Comment by maelchiotti** [comment]
Ok, I'll work on exporting/importing labels (#279) and then improve the script to take that into account.

**Comment by maelchiotti** [comment]
@NripPrajapat The script is ready! You will need to install python and run it through the command line, however.

1. Install python from [here](https://www.python.org/downloads/).
2. Run this command: `py converter.py -a d_notes -i /path/to/dnotes/zip/file.zip -o /path/to/export/file.json`.
3. Import this JSON file into MaterialNotes.

Feel free to tell me if you need more guidance, since I suppose you don't have much experience with running scripts - or maybe none at all.

**Comment by NripPrajapat** [comment]
So I'll need a PC? That's not going to be directly available in the app as a setting?, it'll need to be done separately on PC? Can't I do it without a PC?

**Comment by NripPrajapat** [comment]
> @NripPrajapat The script is ready! You will need to install python and run it through the command line, however.
> 
> 1. Clone this repository in the `dev` branch, or [download it](https://github.com/maelchiotti/LocalMaterialNotes/archive/refs/heads/dev.zip) and unzip it
> 2. Install python from [here](https://www.python.org/downloads/)
> 3. Run this command: `py path/to/docs/external_imports/converter.py -a d_notes -i /path/to/dnotes/zip/file.zip -o /path/to/export/file.json`
> 4. Import this JSON file into MaterialNotes
> 
> Feel free to tell me if you need more guidance, since I suppose you don't have much experience with running scripts - or maybe none at all.

Anyway how to that locally on a computer?

**Comment by NripPrajapat** [comment]
Where should I put the exported file of DNotes in extracted MaterialNotes-dev folder?
Should I put it just next to /docs/external_imports/converter.py or what?

**Comment by NripPrajapat** [comment]
> Where should I put the exported file of 'DNotes' (d_notes.zip) in extracted MaterialNotes-dev folder? Should I put it just next to /docs/external_imports/converter.py or what?

I'm doing that but it is not giving any Json file anywhere, what should it do?

**Comment by NripPrajapat** [comment]
I also tried replacing DNotes file in 'inputs folder' too.

**Comment by NripPrajapat** [comment]
I tried Windows Power shell and Python terminal too.

**Comment by NripPrajapat** [comment]
Also tried DELETED PIN FROM BACKED UP FILE.

**Comment by maelchiotti** [comment]
Sorry for not making it clear this would not be available in the app and you would need a PC. There are 2 reasons for that:
- I don't want to bloat the app with potentially dozens of scripts to convert exports that people will almost never use
- I don't want to spend time developing the UI for that and risk introducing bugs 

Now let's run that script. If you have the python terminal, great, that means python is installed.

The easiest way however would be to use the "Command prompt" app, it's a terminal installed by default on windows.

Then, enter the command I gave you. You have 3 things to replace inside it:
- The path to the converter.py file. Just put the full path to where you unzipped that file.
- The path to the DNotes zip file. It doesn't matter where it is on your computer at all, the script will use the path to read it. (It doesn't need to be next to the converter.my script, and the zip file in the inputs folder is just an example file I keep for testing purposes)
- The path to the output JSON file, that doesn't exist at first, but that the script will create. This can also be anywhere on your computer.

So, assuming you have everything in your Download folder and your Windows username is nrip, you would run that command:

`py C:/users/nrip/Downloads/dev/docs/external_imports/converter.py -a d_notes -i C:/users/nrip/Downloads/my_dnotes_export.zip -o C:/users/nrip/Downloads/my_converted_notes.json`

**Comment by NripPrajapat** [comment]
It says can't open file: python.exe.

**Comment by NripPrajapat** [comment]
ModuleNotFoundError: No module named 'dateutil'

**Comment by NripPrajapat** [comment]
It responds with following


### `Traceback` (most recent call last):
  File "C:\dev\docs\external_imports\converter.py", line 62, in <module>
    main()
    ~~~~^^
  File "C:\dev\docs\external_imports\converter.py", line 22, in main
    from apps.dnotes import convert
  File "C:\dev\docs\external_imports\apps\dnotes.py", line 3, in <module>
    from dateutil.parser import parse
ModuleNotFoundError: No module named 'dateutil'###

**Comment by maelchiotti** [comment]
Forgot that dateutil is not installed by default.

Run: `pip3 install python-dateutil` to install it first!

**Comment by NripPrajapat** [comment]
It finally worked, thanks.
Although I think, it'll be simpler if you just add the import feature in a single release (maybe a beta) and then remove it in proper release, and point it out on readme if anyone want to use import, maybe use that version, that way, your app will not be cluttered and end user will dont have to go through all of this. No bugs too. 😀

**Comment by NripPrajapat** [comment]
It didn't import any label or categories.

**Comment by maelchiotti** [comment]
I'm so glad it worked!

Yes, I agree it would be easier if it was included in the app. I will think about it when I find more time!

And it did not import labels because I didn't release that update yet, forgot to mention this. I'm planning to make a new release in the coming days though!

**Comment by NripPrajapat** [comment]
Whenever you decide to or get to the lock notes feature, please add it in the export, so It would be easier for the user.

**Comment by NripPrajapat** [comment]
It won't import the 'Locked or Unlocked' state of the notes in imported script.

By locking notes means Keep the data of of which note was locked before exporting and if one wants to import, it would also import the notes but in a lock condition.

**Comment by maelchiotti** [comment]
I'll do this when I add locked notes, thanks for the reminder

**Comment by NripPrajapat** [comment]
> It won't import the 'Locked or Unlocked' state of the notes in imported script.
> 
> By locking notes means Keep the data of of which note was locked before exporting and if one wants to import, it would also import the notes but in a lock condition.

@maelchiotti you've added lock app and lock notes feature. So I guess this is the time to add this in the script.
