### ISSUE TITLE
Add a grid view

### ISSUE THREAD

**Issue by maelchiotti** [maelchiotti/LocalMaterialNotes#27]
Add a toggleable grid view that would be usefull for tablets or foldables. It should also be the default on first launch if appropriate.

Probably should use [staggered_grid_view](https://pub.dev/packages/flutter_staggered_grid_view).

Need to watch out for the dismissble tiles.

**Comment by maelchiotti** [comment]
@itsmartashub done in #39, will be available in next release!

**Comment by itsmartashub** [comment]
Yesss, nice job. I was immediately pleased to see from the open issues that you've accepted and almost immediately implemented many suggestions from my Reddit comment "review" of your LMN app. Can't wait to checkout the next version and the grid view 🥹

**Comment by maelchiotti** [comment]
Yes, uploading APKs as artifacts is something I planned to do, it shouldn't take much time so I will add an issue and work on it some time soon!
I will also remove the "Untitled note" label now that you cannot have empty notes anymore.

Glad you like the app and the changes!

**Comment by maelchiotti** [comment]
Also @itsmartashub, for now I've set the grid view to use columns of 384 pixels (and at least two columns) but I eyeballed the width to what felt right on my emulator.

Do you think letting the user choose the number of columns would be useful? I could add a setting for that later.
