### ISSUE TITLE
Change the font of the app (or just the notes)

### ISSUE THREAD

**Issue by NripPrajapat** [maelchiotti/LocalMaterialNotes#270]
Import font and apply it to whole app or just notes.

**Comment by maelchiotti** [comment]
That would require probably too much coding for such a niche feature. I'll leave the issue opened or now in case anyone else is interested so they can like your post.

**Comment by shaaanuu** [comment]
Well, what font do you have in mind?

**Comment by NripPrajapat** [comment]
It should be changeable, selectable from the file system.
If you want to use system font, then whole meaning is lost.
And if you don't wanna do that then at least;
Ubuntu, Google Sans, Nokia Pure, Raleway etc.

**Comment by maelchiotti** [comment]
From a quick search I've done, it's not really possible to pick a system font. However I could include a selection of fonts into the app from which you could choose in the settings, with the most common fonts like you suggested.

That wouldn't be too hard to implement I guess. And I would add a toggle to apply it to the whole app or just the notes.

**Comment by shaaanuu** [comment]
What about adding both feature? One for whole app and one for the notes only.

**Comment by NripPrajapat** [comment]
Try your best.

**Comment by NripPrajapat** [comment]
I would go to that length, to try my best, because itb would charge the whole dynamic of the app, user can customise it, I know it is hard for you, but nothing great comes without hard work.

**Comment by maelchiotti** [comment]
> What about adding both feature? One for whole app and one for the notes only.

@shaaanuu do you mean allowing to choose one font for the app and another one for the notes?

> user can customise it

And yes, I love customization too (that's why the settings are so big for such a simple app), so I definitely want to add this one day!

**Comment by shaaanuu** [comment]
Yeah. One for app UI and one for notes. Seperately.

**Comment by shaaanuu** [comment]
> nothing great comes without hard work.
Yeah true...

**Comment by maelchiotti** [comment]
> Yeah. One for app UI and one for notes. Seperately.

Shouldn't be harder, great suggestion.

**Comment by maelchiotti** [comment]
In the next release you will be able to choose from a dozen fonts, separately for the app and the editor. Of course one of these font is the great Comic Sans MS 😏

**Comment by NripPrajapat** [comment]
Great work, I guess adding open source or CC fonts is hassle free and you don't have to worry about credits issue or licence stuff, but as a user I would love to choose Nokia Pure or Google sans, in case of I just type in my language (take HINDI for example), it won't change anything, so please try adding 'Select font' from file system.

**Comment by maelchiotti** [comment]
I've looked a bit, and I'm pretty certain it's impossible to select fonts from the system.

I can look into the licenses of the fonts you mentioned however, to see if I'm allowed to include them.

**Comment by maelchiotti** [comment]
I've looked a bit, and I'm pretty certain it's impossible to select fonts from the system.

I can look into the licenses of the fonts you mentioned however, to see if I'm allowed to include them.
