### ISSUE TITLE
Confirmation dialog text is OK instead of Cancel

### ISSUE THREAD

**Issue by uli-on** [maelchiotti/LocalMaterialNotes#274]
The dialogue on definitely emptying the bin shows two buttons that offer positive actions but none for cancelling. This is not a translation issue, English and German both have these.

(In case there's a questionnaire here for opening an issue: I'm visiting GitHub with the Octodroid app which creates issues with just 2 empty fields for title and text. Sorry.)

**Comment by maelchiotti** [comment]
Oh I just used the wrong variable, I used the one for OK instead of the one for Cancel. Thanks for letting me know.

**Comment by uli-on** [comment]
No problem, I didn't complain. As a user I recognise your diligence :)
