### ISSUE TITLE
Small improvements and fixes

### ISSUE THREAD

**Issue by maelchiotti** [maelchiotti/LocalMaterialNotes#276]
Labels :

- [x] Add a confirmation dialog when deleting labels (and indicate that labels will be removed from notes when deleted)
- [x] Indicate that labels won't be lost when disabling the feature, just hidden
- [x] Hide labels count on a about sheet when disabled
- [x] Show message if there are no labels to select for a note
- [x] Back action after labels selection dialog closes the app
- [x] Wrong text for label delete menu (see #278)
- [x] Pass the existing label colour to the colour picker

App:

- [ ] #284
- [x] Don't reset sort order when going from creation date to edition date and vice-versa

Miscellaneous:

- [x] Edit changelog to mention Polish addition

**Comment by uli-on** [comment]
> Indicate that labels won't be lost when disabling the feature, just hidden
In the dialogue-to-be-created about deleting a label: maybe indicate that labels will be deleted from notes, too.

**Comment by maelchiotti** [comment]
> I hope it's okay to post my really minor issue findings here.

Yes of course, thanks!

> dialogue always comes up with some default blue, not the colour previously chosen, i. e. altering an existing colour is not possible

I probably forgot to give the existing colour to the dialog, will fix it.

> maybe indicate that labels will be deleted from notes, too

Great idea, will add it.
