### ISSUE TITLE
Change the location of the edit/view mode button

### ISSUE THREAD

**Issue by AppUser000** [maelchiotti/LocalMaterialNotes#277]
Location of the edit/ view toggle button is in the text area and at times it makes it tougher to click the end part of the text or select it as the toggle button overlays it.
![Screenshot_20241123-073650~2](https://github.com/user-attachments/assets/00fafc24-b4c2-4c6e-b526-946baa12272e)
. See the  attached pic to understand what i mean. Toggle bar at the top would make it easier to select the text easily

**Comment by maelchiotti** [comment]
I thought I added some padding at the end of the text, so you could scroll a bit more and select the last line of the text without issue. Looks like it's missing, I'll add it back. This way this shouldn't be an issue.

Or I could also move it to the app bar at the top, as you said, I don't really know what would be best 🤔

**Comment by maelchiotti** [comment]
Ended up moving it to the app bar, makes the editor cleaner I think.
