### ISSUE TITLE
Incorrect button translate in "Manage labels" page

### ISSUE THREAD

**Issue by shishkevichd** [maelchiotti/LocalMaterialNotes#278]
On the `Manage labels` page, the button for deleting a label is labeled `Edit` instead of `Delete`.

![image](https://github.com/user-attachments/assets/fdf48ea9-85f0-4275-ad6f-c085ebb72e6e)

**Comment by maelchiotti** [comment]
Thank you for letting me know, I probably used the wrong variable. I'll close this issue and add this to the many small issues to fix in #276.
