### ISSUE TITLE
Add more actions on multi-selection

### ISSUE THREAD

**Issue by NripPrajapat** [maelchiotti/LocalMaterialNotes#299]
Provide more options, when more than one note is selected, like -
Label
Share
Lock
Export in text format, word, excel or PDF.

**Comment by maelchiotti** [comment]
Progress:

- [ ] Add labels to multiple notes
- [ ] Share multiple notes
- [ ] Export multiple notes as text files

**Comment by maelchiotti** [comment]
Moved exporting to files to a new issue: #337

**Comment by NripPrajapat** [comment]
Find and replace button.
