### ISSUE TITLE
Improve search performance with lots of notes

### ISSUE THREAD

**Issue by NripPrajapat** [maelchiotti/LocalMaterialNotes#301]
Search feature won't work at all. It is broken.

**Comment by maelchiotti** [comment]
Weird, it works on 1.9.1 on my device right now.

Are you on that version as well? You type something and no notes appear?

Can you export the logs from settings > about and upload the file here?

**Comment by NripPrajapat** [comment]
Yes, 1.9.1 (212).

**Comment by maelchiotti** [comment]
Oh I see. How much notes do you have? Probably a lot?

Searching text is always hard to implement, and what I did is clearly not optimised. But it's quite hard to do it better, and when I searched for a library that would do it for me I didn't find any. I'll have to look deeper.

**Comment by maelchiotti** [comment]
@NripPrajapat I have very good news: I have tested a new search feature, and it can search through 5000 big text notes instantly! It even supports typo tolerance (so it will find notes with the word "camputer" that has a typo if you search for "computer"). Can't wait to polish the feature and release it!

**Comment by NripPrajapat** [comment]
Still doesn't do, what it supposed to do. Not searching anything.

**Comment by maelchiotti** [comment]
Oh actually I'm dumb, I completely forgot that it wouldn't work on notes already existing.

The way it works is that it builds an index of the notes from which it searches. But that index is only updated when notes are created or edited.

For the next release, I will add some code that forcefully builds the index if some notes are missing. Sorry for the delay 🙁

**Comment by NripPrajapat** [comment]
Search performance is top notch now,
I'm being greedy but still I would ask for it to Show in order (sort it with ascending or descending order), given criterias of Date (edited, created).

**Comment by maelchiotti** [comment]
Sorting notes in the search view would be great indeed, created a new issue: #343.
