### ISSUE TITLE
Reproducible Build of v1.9.1 failed

### ISSUE THREAD

**Issue by IzzySoft** [maelchiotti/LocalMaterialNotes#304]
Today's RB failed with quite noticable size differences in one of the libraries:

```diff
  -rw-r--r--  0.0 unx 10714752 b-  4991251 defN 1981-01-01 01:01:02 4a340eb2 lib/arm64-v8a/libflutter.so
- -rw-r--r--  0.0 unx  1057056 b-   542025 defN 1981-01-01 01:01:02 b6ac1510 lib/arm64-v8a/libisar.so
+ -rw-r--r--  0.0 unx   890672 b-   449696 defN 1981-01-01 01:01:02 eaa5efe5 lib/arm64-v8a/libisar.so
  -rw-r--r--  0.0 unx     1226 b-      259 defN 1981-01-01 01:01:02 6d6263df assets/flutter_assets/AssetManifest.bin
```

Did any of the build steps change? `.github/workflows/build.yaml` was not updated recently, so we cannot tell.I found `.github/workflows/release.yaml` and tried to adapt from there, but some pieces seem missing: so does it call `bash scripts/isar/fdroid_build_isar.sh` which, in line 36, wants to call to `bash tool/build_android.sh arm64` but that does not exist (maybe you forgot to check in the `tool/` directory and its content?).

Here's the recipe I've prepared so far (to create the arm64 variant), going by that new workflow:

```yaml
build:
  - sed -r '/signingConfigs.release/d' -i android/app/build.gradle
  - git clone https://github.com/rust-lang/rustup.git -b 1.27.1
  - export ANDROID_NDK=/opt/sdk/ndk/${PROVISIONING_NDK}
  - RUST_TOOLCHAIN="$(grep channel rust-toolchain.toml | awk -F'"' '{print $2}')"
  - ${BUILD_REPO_DIR}/rustup/rustup-init.sh -y --default-toolchain ${RUST_TOOLCHAIN} --target aarch64-linux-android
  - fromdos .isar/tool/build_android.sh
  - bash scripts/isar/fdroid_build_isar.sh arm64
  - FLUTTER_VERSION=$(sed -rn 's/^\s*flutter\:\s*([0-9.]+)$/\1/p' pubspec.yaml)
  - git clone -b $FLUTTER_VERSION https://github.com/flutter/flutter
  - export PUB_CACHE=$(pwd)/.pub-cache
  - flutter/bin/flutter config --no-analytics
  - flutter/bin/flutter pub get
  - flutter/bin/dart run build_runner build
  - flutter/bin/flutter gen-l10n
  - flutter/bin/flutter build apk --release --split-per-abi --target-platform="android-arm64"
  - mv build/app/outputs/apk/release/app-arm64-v8a-release-unsigned.apk /outputs/unsigned.apk
```

Any help to keep your app RB is much appreciated – so thanks in advance!

**Comment by maelchiotti** [comment]
And the tool/ directory is inside the .isar directory (see the cd at the top of fdroid_build_isar.sh) which is a git submodule of the isar repository

**Comment by IzzySoft** [comment]
> I forgot to change the parameters of fdroid_build_isar to build for the right architectures.

Ah. But what I wonder is: Why had my original build the isar lib but in a different size? My recipe above then didn't have the lines between the initial `sed` and the `FLUTTER_VERSION`, where did the isar lib come from then?

So I guess, with the next release and things fixed at your end, I can remove those lines again and it would work? Seems strange as I only built for one architecture (arm64), so what lib did I have there? Well, I could of course also wait for linsui's update and have a look there. I wonder why their `.yml` still has 1.7.2 as the newest, though, and lack both 1.8.* releases (which were RB here)…

> And the tool/ directory is inside the .isar directory

Ah, I missed line 45 in that script… OK, then the error I got was just that it didn't find the `rustup` executable, as I didn't "install" rustup but used their init script directly (as that worked fine with several other rust projects here). Guess I'll have to co with `cargo run --release`  then, or switch to `ubuntu:noble` (which would match what you use in your workflow) to directly install `rustup` via `apt`.

**Comment by linsui** [comment]
> where did the isar lib come from then

It's a binary downloaded from pub.

**Comment by IzzySoft** [comment]
Thanks @linsui – yeah, that makes sense. I must have missed that in the logs…

**Comment by linsui** [comment]
@IzzySoft Do you run scanner? You can't see that in the log.

**Comment by IzzySoft** [comment]
It was in the logs, @linsui:

![image](https://github.com/user-attachments/assets/712d1988-bf8c-4ffe-9d58-5d54ac316677)

but I missed it. When you mentioned "downloaded from pub" I remembered to look there :see_no_evil:

**Comment by IzzySoft** [comment]
Thanks to both of you for your help! I've added a second run for v1.9.1 to my builder, so the green shield ("RB confirmed") is up again at IzzyOnDroid.
