### ISSUE TITLE
Fix preferences

### ISSUE THREAD

**Issue by uli-on** [maelchiotti/LocalMaterialNotes#305]
You can't switch the grid view back to list (and vice versa) immediately after using it. You have to tap somewhere else or maybe cause a screen redraw in some way in order to get the list/grid view button to switch view mode for one more time.

App v1.9.1, Android 13, Fairphone 3

**Comment by maelchiotti** [comment]
Thanks for the report. I changed how settings work, got lazy and didn't check every single one... I should have! Will fix it for the next release, probably this week-end.

**Comment by maelchiotti** [comment]
- [ ] Layout
- [ ] Disabled swipe action
