### ISSUE TITLE
Opening links in a browser opens malformed URL

### ISSUE THREAD

**Issue by j-stechmann** [maelchiotti/LocalMaterialNotes#313]
Hi,

When opening a link from a note using long press > open, the URL the browser is opening is malformed.

I've made a short screen recording:
https://github.com/user-attachments/assets/8abba7ce-5fcd-4a9f-9779-35e02174bed7

Funnily enough, the URL is fine when I use the "copy" option after long press.

**Comment by maelchiotti** [comment]
Thanks for the bug report, will look into it
