### ISSUE TITLE
Missing translation for "No labels"

### ISSUE THREAD

**Issue by stepanzak** [maelchiotti/LocalMaterialNotes#326]
![Screenshot_20241222_235336.jpg](https://github.com/user-attachments/assets/c9c5bd82-fac7-4897-bcc1-90a572253f41)

The text "No labels" on the labels managment page when there are no labels isn't translated and I can't find it on Crowdin.

**Comment by maelchiotti** [comment]
Indeed, I forgot to add it to the translations, it's hard coded right now. Let's fix this with today's release.
