### ISSUE TITLE
(KINDA CRITICAL) the bin doesn't work

### ISSUE THREAD

**Issue by stepanzak** [maelchiotti/LocalMaterialNotes#327]
In the latest version (v1.10.0), deleted notes don't go to the bin. I just lost all my notes testing it (I'm dumb and deleted them all + they weren't important)

**Comment by stepanzak** [comment]
Also newly created notes are duplicated to the bin, not being deleted from the main screen. It seems like the bin is now just a clone of the main notes storage.

**Comment by maelchiotti** [comment]
Thank you very much for reporting this. Silly mistake, I changed some code and used the wrong list of notes in the bin. So your deleted notes are not lost. I'm releasing a fix today.
