### ISSUE TITLE
Undo changes

### ISSUE THREAD

**Issue by AI-IMED** [maelchiotti/LocalMaterialNotes#35]
A feature I can never do without, imagine how much frustration you will get when your fingers enter or remove some words or characters for important and sensitive notes like passwords.  
It would be very useful to have an undo button or show a question to confirm that the changes were saved in previously written notes.
I'm talking about showing an undo button or showing a question to confirm that changes are saved to pre-existing notes only, as for notes that are written for the first time, there is no need for an undo button or a confirmation message to save

**Comment by maelchiotti** [comment]
Hi @AI-IMED, the package I use for the editor does support undo/redo, so that should be possible. I will look into it.

**Comment by maelchiotti** [comment]
@AI-IMED done in #40, will be available in next release.
