### ISSUE TITLE
Add to IzzyOnDroid

### ISSUE THREAD

**Issue by Thewisem** [maelchiotti/LocalMaterialNotes#49]
Fdroid is a free and open source app store which is loved by open source enthusiast. I believe this would be a great addition to the store

**Comment by AI-IMED** [comment]
F-Droid is much behind in publishing apps updates unlike IzzyOnDroid

**Comment by maelchiotti** [comment]
Indeed I have heard about IzzyOnDroid a lot lately, I believe it would be a great addition. I'll look into it for the upcoming version or maybe the following one.

**Comment by maelchiotti** [comment]
See https://gitlab.com/IzzyOnDroid/repo/-/issues/536

**Comment by maelchiotti** [comment]
Release per-abis and do the suggested modification

**Comment by maelchiotti** [comment]
Hi @Thewisem and @AI-IMED, the app should soon be available on IzzyOnDroid.

**Comment by Thewisem** [comment]
Thanks for adding it to Izzyondroid. But my phone has armeabi v7a and is incompatible with IzzyonDroid version. If you could. Could you add it to the fdroid official repo?

**Comment by maelchiotti** [comment]
Oh I see the issue. I will look into it for the next release: #72.
