### ISSUE TITLE
Add support for labels

### ISSUE THREAD

**Issue by gasflow** [maelchiotti/LocalMaterialNotes#68]
I would like to feature request about Label because it will make notes organized and I can create labels such as education, workplace, and others. Thank you for doing great app for notes!! 🤗

**Comment by maelchiotti** [comment]
Hi @gasflow, thank you for your feature request!

By "label" I believe you refer to what is often called a "tag", am I right? Then you would be able to sort the notes by those tags.

I want to keep this app quite simple, but Simplenote also does support tags. So I might give it a try, even though I personally wouldn't use that feature.

Finally, feel free to star the repo 😊

**Comment by Ehab-d** [comment]
@maelchiotti Kindly implement the feature as 'Labels' instead of 'Tags,' similar to the approach in Google Keep. You take inspiration about labels from 'Bookmark folder' in Material Files or from the image:
![image](https://github.com/user-attachments/assets/8a3de656-20f5-484e-b06a-f4918548e01f)

**Comment by maelchiotti** [comment]
Thank you for the example @Ehab-d.

To be honest, I'm not planning on adding this soon. It's not an easy task and not something I would use myself, so I'm prioritising other things. But I'll remember your advice on the matter!

**Comment by Ehab-d** [comment]
@maelchiotti I completely understand that. I wanted to confirm that this is one of the best note-taking apps I've ever tried.

**Comment by maelchiotti** [comment]
I'm really glad you like it, thank you for the kind words 🤗

**Comment by maelchiotti** [comment]
@gasflow @Ehab-d @uli-on @itsmartashub Just wanted to let you and anyone interested in that feature that I'm currently working on it! It will take some time, but I'm making sure I release it in a greate state.

**Comment by Ehab-d** [comment]
Thank you for letting us know. ✨

**Comment by maelchiotti** [comment]
@victorbnl helping me test the app would be great! I can tag you (and anyone interested in participating, just like this comment) on the pull request when the feature is completed enough to be usable.

**Comment by victorbnl** [comment]
Sure feel free to tag me when the feature is usable! I may help testing.

**Comment by maelchiotti** [comment]
In case anyone wants to try the feature out : https://github.com/maelchiotti/LocalMaterialNotes/pull/245#issuecomment-2468833177.
