### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by maelchiotti** [maelchiotti/LocalMaterialNotes#72]
Waiting for the request for packaging: https://gitlab.com/fdroid/rfp/-/issues/2781

**Comment by IzzySoft** [comment]
For Fastlane, see #87 (F-Droid's issuebot already complained it's missing – and I bet the next one complaining will be either licaon or linsui :wink:

PS: once merged, it will be used by IzzyOnDroid as well.

**Comment by offa** [comment]
@maelchiotti is there a way to determine the version of flutter used by the release build so the F-Droid can use the exact same version?

**Comment by maelchiotti** [comment]
@offa I always use the latest stable version of Flutter. But maybe errors could happen if a new version is released in the small timeframe between my release and f-droid's build?

According to the docs, I can specify the flutter version used in my pubspec.yaml file (right now I only have the dart SDK version):

```yaml
environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ^3.22.0
```

I guess you could use that to extract the flutter version?

**Comment by offa** [comment]
Yes, I think so! :+1: 

> But maybe errors could happen if a new version is released in the small timeframe between my release and f-droid's build?

The F-Droid build compares the apk to the one on Github, thus may fail if different flutter versions are used.

**Comment by maelchiotti** [comment]
Ok I see. Let me know if you need anything else 😊
