### ISSUE TITLE
Remove space between paragraphs

### ISSUE THREAD

**Issue by 509a** [maelchiotti/LocalMaterialNotes#96]
There is too much extra spacing between new lines

![Screenshot_20240620-104619](https://github.com/maelchiotti/LocalMaterialNotes/assets/16190789/4e1e39e5-53c5-41c4-9a30-417ceccb1d13)

![Screenshot_20240620-110205](https://github.com/maelchiotti/LocalMaterialNotes/assets/16190789/a83b3e92-d557-4c52-9821-f2786aea27fe)

**Comment by maelchiotti** [comment]
Hi, that is the default spacing set by the editor library [fleather](https://github.com/fleather-editor/fleather). I personally like it, it allows me to distinguish new lines from wrapped lines. But I understand not everybody feels the same.

Maybe I could add a toggle in the settings to turn that off, or even provide a few different spacings to choose from. I'll think about it, I don't want to clutter the settings with too many options.

**Comment by maelchiotti** [comment]
Hi @509a, in the next release (coming very soon), you will find a new setting under Settings > Editor to disable the spacing between paragraphs ☺️
